# Generated by Django 6.0.5 on 2026-08-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='main', unique=True)),
                ('ledger', models.JSONField(default=list)),
                ('specific_limits', models.JSONField(default=dict)),
                ('global_limit', models.IntegerField(default=50000)),
                ('total_amount', models.BigIntegerField(default=0)),
                ('valid_lines', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Game State',
            },
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula', models.CharField(blank=True, default='', max_length=50)),
                ('original', models.TextField(default='')),
                ('count', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('is_error', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
