# Generated by Django 6.0.5 on 2026-08-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twodapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationlog',
            name='numbers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
