# Generated by Django 6.0.5 on 2026-08-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twodapp', '0002_operationlog_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestate',
            name='bettor_date',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='bettor_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='operationlog',
            name='bettor_date',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='operationlog',
            name='bettor_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
