# Generated by Django 6.0.5 on 2026-08-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twodapp', '0003_gamestate_bettor_date_gamestate_bettor_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationlog',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
