# Generated by Django 5.2.14 on 2026-08-21 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twodapp', '0004_operationlog_is_canceled'),
    ]

    operations = [
        migrations.CreateModel(
            name='BettorAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password_hash', models.CharField(max_length=128)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('balance', models.IntegerField(default=0)),
                ('hot_limits', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
