# Generated by Django 5.2.14 on 2026-08-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twodapp', '0005_bettoraccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bettoraccount',
            name='last_ip',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='bettoraccount',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bettoraccount',
            name='last_user_agent',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
