# Generated by Django 5.2.14 on 2026-08-21 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twodapp', '0006_bettoraccount_last_ip_bettoraccount_last_seen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationlog',
            name='bettor_username',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
