# Generated by Django 5.2.14 on 2026-08-21 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twodapp', '0007_operationlog_bettor_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(max_length=10)),
                ('sender_name', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
