# Generated by Django 5.2.14 on 2026-08-22 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twodapp', '0009_chatmessage_is_pinned_chatreaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='chat_photos/'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
