# Generated by Django 5.2.14 on 2026-08-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twodapp', '0011_chat_reply_presence'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='chat_voice/'),
        ),
    ]
