# Generated by Django 5.2.14 on 2026-08-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twodapp', '0013_chatmessage_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bettor_username', models.CharField(max_length=50)),
                ('kind', models.CharField(max_length=20)),
                ('message', models.CharField(blank=True, default='', max_length=255)),
                ('group_id', models.CharField(blank=True, default='', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='operationlog',
            name='group_id',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='operationlog',
            name='status',
            field=models.CharField(default='approved', max_length=10),
        ),
    ]
