# Generated by Django 5.2.14 on 2026-08-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twodapp', '0014_playernotification_operationlog_group_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bettoraccount',
            name='multiplier',
            field=models.IntegerField(default=10),
        ),
    ]
