# Generated by Django 5.2.14 on 2026-08-30 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twodapp', '0015_bettoraccount_multiplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bettoraccount',
            name='multiplier',
        ),
    ]
