# Generated by Django 5.2.14 on 2026-08-30 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twodapp', '0016_remove_bettoraccount_multiplier'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlayerNotification',
        ),
        migrations.RemoveField(
            model_name='operationlog',
            name='group_id',
        ),
        migrations.RemoveField(
            model_name='operationlog',
            name='status',
        ),
    ]
