# Generated by Django 5.2.14 on 2026-09-05 09:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twodapp', '0017_delete_playernotification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula', models.CharField(blank=True, default='', max_length=50)),
                ('original', models.TextField(default='')),
                ('numbers', models.JSONField(blank=True, default=list)),
                ('count', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('is_error', models.BooleanField(default=False)),
                ('is_canceled', models.BooleanField(default=False)),
                ('bettor_name', models.CharField(blank=True, default='', max_length=100)),
                ('bettor_date', models.CharField(blank=True, default='', max_length=10)),
                ('bettor_username', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('archived_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-archived_at'],
            },
        ),
    ]
